import { useEffect, useMemo, useState } from 'react'
import { followUps, lessonInfo, prompts, type Lesson, type PromptCard } from './data/prompts'
import kimbapMenuImage from './assets/kimbap-cheonguk-menu.png'

type Fields = { subject:string; role:string; context:string; goal:string; audience:string; customConditions:string; customFormat:string; selectedConditions:string[]; selectedFormats:string[]; source:string; source2:string }
const blank = ():Fields => ({subject:'',role:'',context:'',goal:'',audience:'',customConditions:'',customFormat:'',selectedConditions:[],selectedFormats:[],source:'',source2:''})
const initial = (p:PromptCard):Fields => ({subject:p.title,role:p.role,context:p.context,goal:p.goal,audience:p.audience,customConditions:'',customFormat:'',selectedConditions:[],selectedFormats:[],source:p.id==='menu'?'':p.sourceData || '',source2:p.secondSourceLabel ? '' : ''})
const fieldInfo: {key:keyof Fields; label:string; help:string; large?:boolean}[] = [
  {key:'subject',label:'내 주제·관심사',help:'알아보고 싶은 주제를 적으면 조건 추천이 바뀝니다.'},{key:'role',label:'역할',help:'AI가 어떤 관점으로 답하면 좋을까요?'},{key:'context',label:'상황·맥락',help:'지금 어떤 상황인가요?'},{key:'goal',label:'목표',help:'무엇을 얻고 싶나요?'},{key:'audience',label:'대상',help:'누가 이 결과를 사용하나요?'}
]

function assemble(f:Fields) { const conditions=[...f.selectedConditions,...f.customConditions.split('\n').filter(Boolean)].map(x=>`- ${x.trim()}`).join('\n'); const formats=[...f.selectedFormats,...f.customFormat.split('\n').filter(Boolean)].join(', '); const blocks:[string,string][] = [['주제',f.subject],['역할',f.role],['상황·맥락',f.context],['목표',f.goal],['대상',f.audience],['조건',conditions],['출력 형식',formats],['입력 자료',f.source],['두 번째 입력 자료',f.source2]]; return blocks.filter(([,v])=>v.trim()).map(([h,v])=>`[${h}]\n${v.trim()}`).join('\n\n') }

export default function App(){
 const [lesson,setLesson]=useState<Lesson|'all'>(1),[query,setQuery]=useState(''),[selectedId,setSelectedId]=useState(prompts[0].id),[fields,setFields]=useState<Fields>(()=>initial(prompts[0])),[large,setLarge]=useState(false),[help,setHelp]=useState(true),[toast,setToast]=useState(''),[manualPrompt,setManualPrompt]=useState(false),[editedPrompt,setEditedPrompt]=useState(()=>assemble(initial(prompts[0])))
 const cards=useMemo(()=>prompts.filter(p=>(lesson==='all'||p.lesson===lesson)&&`${p.title} ${p.category} ${p.description}`.toLowerCase().includes(query.toLowerCase())),[lesson,query]); const selected=prompts.find(p=>p.id===selectedId)||prompts[0]; const prompt=assemble(fields)
 useEffect(()=>{if(!manualPrompt)setEditedPrompt(prompt)},[prompt,manualPrompt])
 const choose=(p:PromptCard)=>{setSelectedId(p.id);setFields(initial(p));setManualPrompt(false);setTimeout(()=>document.getElementById('builder')?.scrollIntoView({behavior:'smooth'}),0)}
 const update=(key:keyof Fields,value:string)=>setFields(v=>({...v,[key]:value}))
 const toggleChoice=(key:'selectedConditions'|'selectedFormats',value:string)=>setFields(v=>({...v,[key]:v[key].includes(value)?v[key].filter(x=>x!==value):[...v[key],value]}))
 const formatOptions=Array.from(new Set([selected.outputFormat,'표','번호 목록','체크리스트','3줄 요약','1페이지 브리핑','쉬운 설명']))
 const topicText=`${fields.subject} ${fields.context} ${fields.goal}`.toLowerCase()
 const suggestedConditions=[
   ...( /(동탄|여행|나들이|외출|주말|장소)/.test(topicText) ? ['이동 시간을 포함','날씨가 나쁠 때의 대안','가까운 장소 우선'] : []),
   ...( /(음식|메뉴|식당|요리)/.test(topicText) ? ['알레르기·못 먹는 음식 확인','예산 안에서 총액 계산','메뉴판에 없는 내용 만들지 않기'] : []),
   ...( /(뉴스|ai|인공지능|트렌드|기업|주식|부동산|정책|지원)/.test(topicText) ? ['최신 날짜 표시','공식 출처 우선','확인되지 않은 내용은 확인 필요로 표시'] : []),
   ...( /(아이|부모|어르신|초등|학생)/.test(topicText) ? ['쉬운 말 사용','대상 연령에 맞춰 설명','안전·휴식 고려'] : []),
 ]
 const conditionOptions=Array.from(new Set([...selected.conditions,...suggestedConditions]))
 const copy=async(text:string,message:string)=>{try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(text);else throw 0;setToast(message)}catch{const a=document.createElement('textarea');a.value=text;a.style.cssText='position:fixed;opacity:0';document.body.append(a);a.select();const ok=document.execCommand('copy');a.remove();setToast(ok?message:'복사하지 못했어요. 내용을 길게 눌러 직접 복사해 주세요.')}setTimeout(()=>setToast(''),2500)}
 return <main className={`studio ${large?'large-text':''}`}><header><a href="#top" className="logo">생활형 AI <b>프롬프트 실습실</b></a><button className="text-button" onClick={()=>setLarge(!large)}>{large?'기본 글씨':'큰 글씨'} 보기</button></header>
 <section id="top" className="intro"><p className="kicker">DONGTAN 8-DONG AI CLASS</p><h1>내 상황과 조건을 넣어<br/><em>바로 사용할 프롬프트</em>를 만들어보세요.</h1><p>주제 선택 → 내용 수정 → 프롬프트 복사 → ChatGPT 또는 Gemini에서 실행</p></section>
 <nav className="lesson-tabs" aria-label="교시 선택">{(['all',1,2,3] as const).map(l=><button key={String(l)} className={lesson===l?'active':''} onClick={()=>setLesson(l)}>{l==='all'?'전체 보기':`${lessonInfo[l].label} · ${lessonInfo[l].name}`}</button>)}</nav>
 <section className="finder"><label><span>⌕</span><input aria-label="실습 주제 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="주말, 메뉴판, 뉴스, 주식, 부동산, AI 트렌드 검색"/></label><small>{cards.length}개의 실습 주제</small></section>
 <section className="cards" aria-label="실습 주제">{cards.map(p=><article className={`card lesson-${p.lesson}`} key={p.id}><div><span>{lessonInfo[p.lesson].label}</span><span>{p.category}</span></div><h2>{p.title}</h2><p>{p.description}</p><footer><span>⏱ {p.duration}</span><span>난이도 {p.difficulty}</span>{p.requiresSource&&<span>자료 입력</span>}</footer><button onClick={()=>choose(p)}>프롬프트 만들기 →</button></article>)}</section>
 <section className="builder-wrap" id="builder"><div className="builder-title"><div><p className="kicker">STEP 2 · 내 조건으로 설계하기</p><h2>{selected.title}</h2><p>{selected.description}</p></div><button className="reset" onClick={()=>{setFields(blank());setManualPrompt(false)}}>입력 내용 초기화</button></div>
 {help&&<aside className="help"><div><b>AI 6요소가 무엇인가요?</b><p>역할·상황·목표·대상·조건·형식은 AI가 판단하는 데 필요한 정보를 알려줍니다. 모두 채울 필요는 없어요.</p></div><button onClick={()=>setHelp(false)} aria-label="초보자 도움말 숨기기">×</button></aside>}
 {!help&&<button className="help-show" onClick={()=>setHelp(true)}>AI 6요소 도움말 보기</button>}
 <div className="builder-grid"><section className="editor" aria-label="프롬프트 입력 항목">{fieldInfo.map(item=><label key={item.key}><b>{item.label}</b><small>{item.help}</small><input value={fields[item.key] as string} onChange={e=>update(item.key,e.target.value)}/></label>)}
 <fieldset className="choice-field"><legend>조건 선택</legend><small>카드에 맞는 기본 조건과 ‘내 주제·관심사’에 따른 추천 조건입니다. 필요한 것을 여러 개 골라보세요.</small><div className="choice-chips">{conditionOptions.map(value=><button type="button" key={value} className={fields.selectedConditions.includes(value)?'selected':''} onClick={()=>toggleChoice('selectedConditions',value)} aria-pressed={fields.selectedConditions.includes(value)}>{fields.selectedConditions.includes(value)?'✓ ':''}{value}</button>)}</div><textarea value={fields.customConditions} onChange={e=>update('customConditions',e.target.value)} placeholder="기타 조건을 직접 작성하세요. 한 줄에 하나씩 적어주세요." aria-label="기타 조건 직접 작성"/></fieldset>
 <fieldset className="choice-field"><legend>출력 형식 선택</legend><small>원하는 결과 모양을 여러 개 고를 수 있습니다.</small><div className="choice-chips">{formatOptions.map(value=><button type="button" key={value} className={fields.selectedFormats.includes(value)?'selected':''} onClick={()=>toggleChoice('selectedFormats',value)} aria-pressed={fields.selectedFormats.includes(value)}>{fields.selectedFormats.includes(value)?'✓ ':''}{value}</button>)}</div><input value={fields.customFormat} onChange={e=>update('customFormat',e.target.value)} placeholder="기타 출력 형식을 직접 작성하세요" aria-label="기타 출력 형식 직접 작성"/></fieldset>
 {selected.requiresSource&&<div className="source"><div><b>{selected.sourceLabel}</b><small>{selected.id==='voice'?'ChatGPT 음성 대화에서 말한 뒤, 화면에 나온 전사문을 복사해서 이곳에 붙여 넣어 보세요. 이 웹앱은 음성을 저장하거나 전송하지 않습니다.':selected.id==='menu'?'아래 메뉴판 사진을 저장한 뒤 ChatGPT 또는 Gemini에 첨부해 보세요. 필요한 메뉴와 가격을 AI가 읽도록 요청할 수 있습니다.':'AI가 읽고 정리할 자료를 넣어주세요. 개인정보는 삭제하거나 익명으로 바꾸는 것이 좋습니다.'}</small></div>{selected.id==='menu'&&<figure className="menu-image"><img src={kimbapMenuImage} alt="김밥천국 메뉴판"/><figcaption><a href={kimbapMenuImage} download="김밥천국-메뉴판.png">메뉴판 사진 저장 ↓</a></figcaption></figure>}{selected.id==='voice'&&<a className="voice-guide" href="https://chatgpt.com/" target="_blank" rel="noreferrer">ChatGPT에서 음성 대화 열기 ↗</a>}<textarea aria-label={`${selected.sourceLabel} 입력`} value={fields.source} onChange={e=>update('source',e.target.value)} placeholder={selected.id==='menu'?'사진을 AI에 첨부한 뒤, 특별히 고려할 메뉴·예산·인원을 여기에 적어보세요.':undefined}/>{selected.secondSourceLabel&&<><b>{selected.secondSourceLabel}</b><textarea aria-label={`${selected.secondSourceLabel} 입력`} value={fields.source2} onChange={e=>update('source2',e.target.value)}/></>}<div className="source-actions">{selected.sourceData&&<button onClick={()=>update('source',selected.sourceData||'')}>예시 자료 불러오기</button>}<button onClick={()=>update('source','')}>자료 지우기</button><button onClick={()=>copy(fields.source,'입력 자료를 복사했어요.')}>입력 자료만 복사</button></div></div>}</section>
 <section className="preview"><div className="preview-head"><div><p className="kicker">STEP 3 · 완성된 프롬프트</p><h3>문장을 직접 고친 뒤 복사하세요</h3></div><button onClick={()=>copy(editedPrompt,'완성된 프롬프트를 복사했어요.')}>프롬프트 복사</button></div><p className="edit-hint">아래 문장을 직접 수정할 수 있습니다. 직접 고친 뒤에는 왼쪽 선택 항목이 자동으로 덮어쓰지 않습니다.</p><textarea className="prompt-editor" aria-label="완성된 프롬프트 직접 수정" value={editedPrompt} onChange={e=>{setEditedPrompt(e.target.value);setManualPrompt(true)}} placeholder="왼쪽 항목을 채우면 여기에 완성된 프롬프트가 나타납니다."/>{manualPrompt&&<button className="restore" onClick={()=>{setManualPrompt(false);setEditedPrompt(prompt)}}>자동 생성 문장으로 되돌리기</button>}<div className="checklist"><b>복사 전 확인</b><label><input type="checkbox"/> 원하는 결과가 명확한가요?</label><label><input type="checkbox"/> 꼭 지켜야 할 조건을 넣었나요?</label><label><input type="checkbox"/> 개인정보를 삭제했나요?</label></div><div className="follow"><b>결과가 마음에 들지 않을 때</b>{selected.followUps.map((text,i)=><div key={i}><span>{text}</span><button onClick={()=>copy(text,'수정 요청을 복사했어요.')}>복사</button></div>)}</div></section></div></section>{toast&&<div role="status" className="toast">{toast}</div>}</main>
}
